# Generated by Django 5.1.1 on 2024-09-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeJogador', models.CharField(max_length=100)),
                ('tentativas', models.IntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
